### ISSUE TITLE
Compiler errors with undeclared symbols

### ISSUE THREAD

**Issue by bangerth** [geodynamics/Rayleigh#85]
In my experiments with using cmake, I run into two compiler errors on lines 111 and 130 of `src/Diagnostics/Diagnostics_energy_flux.F90`. The first of these lines looks like this:
```
        If (compute_quantity(Enth_flux_radial)) Then
```
The error reads
```
/home/bangerth/p/deal.II/1/projects/Rayleigh/src/Diagnostics/Diagnostics_Energy_Flux.F90:111:45:

         If (compute_quantity(Enth_flux_radial)) Then
                                             1
Error: Symbol ‘enth_flux_radial’ at (1) has no IMPLICIT type
/home/bangerth/p/deal.II/1/projects/Rayleigh/src/Diagnostics/Diagnostics_Energy_Flux.F90:130:49:

         If (compute_quantity(thermalE_flux_radial)) Then
                                                 1
Error: Symbol ‘thermale_flux_radial’ at (1) has no IMPLICIT type
```

The compiler is correct: These symbols don't appear to be declared anywhere, in contrast to the symbols in similar `if` statements above and below.

How is this supposed to compile and why do I not observe this with the current build system? Is this file simply not compiled?

**Comment by orvedahl** [comment]
The current build system compiles properly because the Diagnostics_Energy_Flux.F90 file is not listed in the src/object_list file. The object_list file holds the file dependencies and is imported into the proper makefile at build time. I'm willing to bet this file is not explicitly needed anymore, but am not completely sure.

I believe all the quantities in the Diagnostics_Energy_Flux.F90 file have been moved to Diagnostics_Thermal_Equation.F90. For example, the "Enth_flux_radial" quantity is the exact same as the "enth_flux_r" in the Diagnostics_Thermal_Equation.F90 file.

**Comment by bangerth** [comment]
I've come to the same realization that the current build system simply doesn't compile this file. Another file that is not compiled is `Physics/Linear_Terms_Cart.F90` because it uses a non-existing module `Nondimensionalization`.

As these examples show, files that are not compiled quickly bit-rot. Can we remove them?
